apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    app: nginx             # Make sure this matches your pod labels
  ports:
    - protocol: TCP
      port: 80             # Service port
      targetPort: 80       # Pod container port
  type: ClusterIP          # Default type, can be omitted

